# Generated by Django 5.2.3 on 2025-06-18 19:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã người dùng')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Tên đăng nhập')),
                ('password', models.CharField(max_length=128, verbose_name='Mật khẩu')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('receptionist', 'Lễ tân'), ('doctor', 'Bác sĩ'), ('patient', 'Bệnh nhân')], default='patient', max_length=20, verbose_name='Vai trò')),
                ('status', models.BooleanField(default=False, verbose_name='Trạng thái hoạt động')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('gender', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', 'Khác')], default='Nam', max_length=10, verbose_name='Giới tính')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('birth_day', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('phone', models.CharField(max_length=10, unique=True, verbose_name='Số điện thoại')),
                ('gmail', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='DegreeExamFee',
            fields=[
                ('degree_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã bằng cấp')),
                ('degree_name', models.CharField(max_length=50, verbose_name='Tên bằng cấp')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Phí khám bệnh')),
            ],
            options={
                'verbose_name': 'Bằng cấp và phí khám bệnh',
                'db_table': 'degree_exam_fee',
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã xét nghiệm')),
                ('test_name', models.CharField(max_length=100, verbose_name='Tên xét nghiệm')),
                ('test_description', models.TextField(verbose_name='Mô tả xét nghiệm')),
                ('test_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá xét nghiệm')),
                ('test_category', models.CharField(max_length=100, verbose_name='Loại xét nghiệm')),
            ],
            options={
                'verbose_name': 'Xét nghiệm',
                'verbose_name_plural': 'Xét nghiệm',
                'db_table': 'lab_test',
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('medication_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã thuốc')),
                ('medication_name', models.CharField(max_length=100, verbose_name='Tên thuốc')),
                ('medication_description', models.TextField(verbose_name='Mô tả thuốc')),
                ('medication_unit', models.CharField(max_length=20, verbose_name='Đơn vị thuốc')),
                ('medication_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá thuốc')),
                ('recommended_dosage', models.CharField(max_length=50, verbose_name='Liều lượng khuyến nghị')),
                ('expiration_date', models.DateField(verbose_name='Ngày hết hạn')),
                ('stock_quantity', models.IntegerField(verbose_name='Số lượng tồn kho')),
                ('medication_category', models.CharField(max_length=100, verbose_name='Loại thuốc')),
            ],
            options={
                'verbose_name': 'Thuốc',
                'verbose_name_plural': 'Thuốc',
                'db_table': 'medications',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã lịch hẹn')),
                ('appointment_day', models.DateField(default=datetime.date.today, verbose_name='Ngày hẹn')),
                ('appointment_status', models.CharField(choices=[('pending', 'Đã đặt cọc'), ('confirmed', 'Đã xác nhận'), ('cancelled', 'Đã hủy'), ('unpaid_deposit', 'Chưa đặt cọc'), ('full', 'Đang tiến hành'), ('done', 'Đã hoàn thành')], default='unpaid_deposit', max_length=20, verbose_name='Trạng thái lịch hẹn')),
                ('appointment_time', models.TimeField(default=datetime.time(12, 0), verbose_name='Giờ hẹn')),
                ('appointment_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo lịch hẹn')),
                ('appointment_updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật lịch hẹn')),
                ('doctor_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_doctor', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng bác sĩ')),
                ('patient_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_patient', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng bệnh nhân')),
            ],
            options={
                'verbose_name': 'Lịch hẹn',
                'verbose_name_plural': 'Lịch hẹn',
                'db_table': 'appointments',
                'ordering': ['-appointment_day', '-appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã hồ sơ bệnh án')),
                ('record_status', models.CharField(choices=[('done', 'đã xong'), ('loading', 'đang tiến hành')], default='loading', max_length=20, verbose_name='Trạng thái hồ sơ bệnh án')),
                ('record_note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('diagnosis', models.TextField(blank=True, null=True, verbose_name='Chẩn đoán')),
                ('treatment', models.TextField(blank=True, null=True, verbose_name='Điều trị')),
                ('record_result', models.TextField(blank=True, null=True, verbose_name='Kết quả')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='hospital.appointment', verbose_name='Lịch hẹn')),
            ],
            options={
                'verbose_name': 'Hồ sơ bệnh án',
                'verbose_name_plural': 'Hồ sơ bệnh án',
                'db_table': 'medical_records',
            },
        ),
        migrations.CreateModel(
            name='OtpUsers',
            fields=[
                ('otp_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'otp_users',
            },
        ),
        migrations.CreateModel(
            name='PatientTest',
            fields=[
                ('patient_test_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã xét nghiệm bệnh nhân')),
                ('test_result', models.TextField(blank=True, null=True, verbose_name='Kết quả xét nghiệm')),
                ('test_date', models.DateField(blank=True, null=True, verbose_name='Ngày xét nghiệm')),
                ('test_status', models.CharField(choices=[('Pending', 'Đang chờ thanh toán'), ('Done', 'Đã xong'), ('Waiting', 'Đang chờ kết quả'), ('Cancelled', 'Đã hủy'), ('In Progress', 'Đang tiến hành')], default='Pending', max_length=20, verbose_name='Trạng thái xét nghiệm')),
                ('performed_by_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performed_tests', to=settings.AUTH_USER_MODEL, verbose_name='Bác sĩ thực hiện xét nghiệm')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_tests', to='hospital.medicalrecord', verbose_name='Hồ sơ bệnh án')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_tests', to='hospital.labtest', verbose_name='Xét nghiệm')),
            ],
            options={
                'verbose_name': 'Xét nghiệm bệnh nhân',
                'verbose_name_plural': 'Xét nghiệm bệnh nhân',
                'db_table': 'patient_tests',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã hóa đơn thanh toán')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tổng số tiền')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('paid', 'Đã thanh toán')], default='unpaid', max_length=20, verbose_name='Trạng thái thanh toán')),
                ('payment_type', models.CharField(blank=True, choices=[('test', 'Xét nghiệm'), ('prescription', 'thuốc'), ('deposit', 'Đặt cọc'), ('exam', 'Tiền khám')], default='deposit', max_length=20, null=True, verbose_name='Loại thanh toán')),
                ('order_code', models.CharField(max_length=20, unique=True, verbose_name='Mã đơn hàng')),
                ('payment_method', models.CharField(blank=True, choices=[('banking', 'Chuyển khoản'), ('cash', 'Tiền mặt')], max_length=50, null=True, verbose_name='Phương thức thanh toán')),
                ('payment_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian thanh toán')),
                ('vnp_create_date', models.CharField(blank=True, max_length=14, null=True, verbose_name='Ngày tạo VNPAY')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hospital.appointment', verbose_name='Lịch hẹn')),
            ],
            options={
                'verbose_name': 'Hóa đơn thanh toán',
                'verbose_name_plural': 'Hóa đơn thanh toán',
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã chi tiết thanh toán')),
                ('service_type', models.CharField(max_length=50, verbose_name='Loại dịch vụ')),
                ('service_id', models.IntegerField(verbose_name='Mã dịch vụ')),
                ('service_name', models.CharField(max_length=255, verbose_name='Tên dịch vụ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số tiền')),
                ('detail_quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng dịch vụ')),
                ('detail_status', models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('paid', 'Đã thanh toán')], default='unpaid', max_length=20, verbose_name='Trạng thái chi tiết thanh toán')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='hospital.payment', verbose_name='Hóa đơn thanh toán')),
            ],
            options={
                'verbose_name': 'Chi tiết thanh toán',
                'verbose_name_plural': 'Chi tiết thanh toán',
                'db_table': 'payment_details',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã đơn thuốc')),
                ('prescription_status', models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('paid', 'Đã thanh toán'), ('done', 'Đã nhận (hoàn tất)')], default='unpaid', max_length=20, verbose_name='Trạng thái đơn thuốc')),
                ('instructions', models.TextField(verbose_name='Lời dặn của bác sĩ')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='hospital.medicalrecord', verbose_name='Hồ sơ bệnh án')),
            ],
            options={
                'verbose_name': 'Đơn thuốc',
                'verbose_name_plural': 'Đơn thuốc',
                'db_table': 'prescriptions',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionDetail',
            fields=[
                ('detail_p_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã chi tiết thuốc')),
                ('quantity', models.IntegerField(verbose_name='Số lượng')),
                ('dosage', models.CharField(max_length=100, verbose_name='Liều dùng')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_details', to='hospital.medication', verbose_name='Thuốc')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='hospital.prescription', verbose_name='Đơn thuốc')),
            ],
            options={
                'verbose_name': 'Chi tiết thuốc',
                'verbose_name_plural': 'Chi tiết thuốc',
                'db_table': 'prescription_details',
            },
        ),
        migrations.CreateModel(
            name='ProfileDoctor',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã hồ sơ bác sĩ')),
                ('specialty', models.CharField(max_length=50, verbose_name='Chuyên khoa')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Ảnh đại diện')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.degreeexamfee', verbose_name='Bằng cấp')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hồ sơ bác sĩ',
                'verbose_name_plural': 'Hồ sơ bác sĩ',
                'db_table': 'profile_doctors',
            },
        ),
    ]
