# Generated by Django 5.1.7 on 2025-05-30 16:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('receptionist', 'Receptionist'), ('doctor', 'Doctor'), ('patient', 'Patient')], default='patient', max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('birth_day', models.DateField()),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('gmail', models.EmailField(max_length=254, unique=True)),
                ('specialty', models.CharField(blank=True, max_length=50, null=True)),
                ('degree', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('test_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('test_category', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'lab_test',
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('medication_id', models.AutoField(primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=100)),
                ('medication_description', models.TextField()),
                ('medication_unit', models.CharField(max_length=20)),
                ('medication_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recommended_dosage', models.CharField(max_length=50)),
                ('expiration_date', models.DateField()),
                ('stock_quantity', models.IntegerField()),
                ('medication_category', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'medications',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_day', models.DateField(default=datetime.date.today)),
                ('appointment_status', models.CharField(default='pending', max_length=20)),
                ('appointment_time', models.TimeField(default=datetime.time(12, 0))),
                ('description', models.TextField(blank=True, null=True)),
                ('appointment_created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment_updated_at', models.DateTimeField(auto_now=True)),
                ('doctor_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_doctor', to=settings.AUTH_USER_MODEL)),
                ('patient_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_patient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'appointments',
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('record_status', models.CharField(max_length=20)),
                ('record_note', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('treatment', models.TextField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='hospital.appointment')),
            ],
            options={
                'db_table': 'medical_records',
            },
        ),
        migrations.CreateModel(
            name='OtpUsers',
            fields=[
                ('otp_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientTest',
            fields=[
                ('patient_test_id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.TextField(blank=True, null=True)),
                ('test_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('performed_by_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performed_tests', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_tests', to='hospital.medicalrecord')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_tests', to='hospital.labtest')),
            ],
            options={
                'db_table': 'patient_tests',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_timestamp', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hospital.appointment')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_type', models.CharField(max_length=50)),
                ('service_id', models.IntegerField()),
                ('service_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='hospital.payment')),
            ],
            options={
                'db_table': 'payment_details',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.CharField(max_length=50)),
                ('dosage', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('instructions', models.TextField()),
                ('frequency', models.CharField(max_length=50)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='hospital.medication')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='hospital.medicalrecord')),
            ],
            options={
                'db_table': 'prescription',
            },
        ),
    ]
