# Generated by Django 5.1.7 on 2025-06-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_code',
            field=models.CharField(default='ORD123456', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
