# Generated by Django 5.1.7 on 2025-06-17 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profiledoctor',
            table='profile_doctors',
        ),
    ]
