# Generated by Django 5.1.7 on 2025-06-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_payment_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='detail_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='detail_status',
            field=models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('paid', 'Đã thanh toán')], default='unpaid', max_length=20),
        ),
    ]
