# Generated by Django 5.1.7 on 2025-06-05 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_alter_payment_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='service_id',
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='labtest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_details', to='hospital.labtest'),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_details', to='hospital.prescription'),
        ),
    ]
