# Generated by Django 5.1.7 on 2025-06-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_remove_paymentdetail_service_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='labtest',
        ),
        migrations.RemoveField(
            model_name='paymentdetail',
            name='prescription',
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='service_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
