# Generated by Django 5.1.7 on 2025-06-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_remove_paymentdetail_labtest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='vnp_create_date',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
