# Generated by Django 5.1.7 on 2025-06-08 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_payment_vnp_create_date_user_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpusers',
            old_name='is_phone_verified',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='patienttest',
            old_name='result',
            new_name='test_result',
        ),
        migrations.RenameField(
            model_name='patienttest',
            old_name='status',
            new_name='test_status',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='quantity',
            new_name='prescription_quantity',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='result',
        ),
        migrations.AddField(
            model_name='labtest',
            name='test_description',
            field=models.TextField(default='no'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='record_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='hospital.appointment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='duration',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='gmail',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
