# Generated by Django 5.1.7 on 2025-06-10 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_rename_is_phone_verified_otpusers_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-appointment_day', '-appointment_time']},
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='record_status',
            field=models.CharField(choices=[('done', 'đã xong'), ('loading', 'đang tiến hành')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patienttest',
            name='performed_by_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performed_tests', to=settings.AUTH_USER_MODEL),
        ),
    ]
