# Generated by Django 5.1.7 on 2025-06-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienttest',
            name='test_status',
            field=models.CharField(choices=[('Pending', 'Đang chờ thanh toán'), ('Done', 'Đã xong'), ('Waiting', 'Đang chờ kết quả'), ('Cancelled', 'Đã hủy'), ('In Progress', 'Đang tiến hành')], default='Pending', max_length=20),
        ),
    ]
