# Generated by Django 5.1.7 on 2025-06-10 05:12

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_alter_patienttest_test_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-appointment_day', '-appointment_time'], 'verbose_name': 'Lịch hẹn', 'verbose_name_plural': 'Lịch hẹn'},
        ),
        migrations.AlterModelOptions(
            name='labtest',
            options={'verbose_name': 'Xét nghiệm', 'verbose_name_plural': 'Xét nghiệm'},
        ),
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'verbose_name': 'Hồ sơ bệnh án', 'verbose_name_plural': 'Hồ sơ bệnh án'},
        ),
        migrations.AlterModelOptions(
            name='medication',
            options={'verbose_name': 'Thuốc', 'verbose_name_plural': 'Thuốc'},
        ),
        migrations.AlterModelOptions(
            name='patienttest',
            options={'verbose_name': 'Xét nghiệm bệnh nhân', 'verbose_name_plural': 'Xét nghiệm bệnh nhân'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Hóa đơn thanh toán', 'verbose_name_plural': 'Hóa đơn thanh toán'},
        ),
        migrations.AlterModelOptions(
            name='paymentdetail',
            options={'verbose_name': 'Chi tiết thanh toán', 'verbose_name_plural': 'Chi tiết thanh toán'},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'verbose_name': 'Đơn thuốc', 'verbose_name_plural': 'Đơn thuốc'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Người dùng', 'verbose_name_plural': 'Người dùng'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo lịch hẹn'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_day',
            field=models.DateField(default=datetime.date.today, verbose_name='Ngày hẹn'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Mã lịch hẹn'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(choices=[('pending', 'Đang chờ'), ('confirmed', 'Đã xác nhận'), ('cancelled', 'Đã hủy'), ('completed', 'Đã hoàn thành')], default='pending', max_length=20, verbose_name='Trạng thái lịch hẹn'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(default=datetime.time(12, 0), verbose_name='Giờ hẹn'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật lịch hẹn'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_doctor', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng bác sĩ'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_patient', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng bệnh nhân'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='test_category',
            field=models.CharField(max_length=100, verbose_name='Loại xét nghiệm'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='test_description',
            field=models.TextField(verbose_name='Mô tả xét nghiệm'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='test_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Mã xét nghiệm'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='test_name',
            field=models.CharField(max_length=100, verbose_name='Tên xét nghiệm'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='test_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá xét nghiệm'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='hospital.appointment', verbose_name='Lịch hẹn'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='diagnosis',
            field=models.TextField(blank=True, null=True, verbose_name='Chẩn đoán'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='record_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Mã hồ sơ bệnh án'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='record_note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='record_result',
            field=models.TextField(blank=True, null=True, verbose_name='Kết quả'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='record_status',
            field=models.CharField(choices=[('done', 'đã xong'), ('loading', 'đang tiến hành')], default='loading', max_length=20, verbose_name='Trạng thái hồ sơ bệnh án'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='treatment',
            field=models.TextField(blank=True, null=True, verbose_name='Điều trị'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='expiration_date',
            field=models.DateField(verbose_name='Ngày hết hạn'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='medication_category',
            field=models.CharField(max_length=100, verbose_name='Loại thuốc'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='medication_description',
            field=models.TextField(verbose_name='Mô tả thuốc'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='medication_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Mã thuốc'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='medication_name',
            field=models.CharField(max_length=100, verbose_name='Tên thuốc'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='medication_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá thuốc'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='medication_unit',
            field=models.CharField(max_length=20, verbose_name='Đơn vị thuốc'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='recommended_dosage',
            field=models.CharField(max_length=50, verbose_name='Liều lượng khuyến nghị'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='stock_quantity',
            field=models.IntegerField(verbose_name='Số lượng tồn kho'),
        ),
        migrations.AlterField(
            model_name='patienttest',
            name='patient_test_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Mã xét nghiệm bệnh nhân'),
        ),
        migrations.AlterField(
            model_name='patienttest',
            name='performed_by_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performed_tests', to=settings.AUTH_USER_MODEL, verbose_name='Bác sĩ thực hiện xét nghiệm'),
        ),
        migrations.AlterField(
            model_name='patienttest',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_tests', to='hospital.medicalrecord', verbose_name='Hồ sơ bệnh án'),
        ),
        migrations.AlterField(
            model_name='patienttest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_tests', to='hospital.labtest', verbose_name='Xét nghiệm'),
        ),
        migrations.AlterField(
            model_name='patienttest',
            name='test_date',
            field=models.DateField(verbose_name='Ngày xét nghiệm'),
        ),
        migrations.AlterField(
            model_name='patienttest',
            name='test_result',
            field=models.TextField(blank=True, null=True, verbose_name='Kết quả xét nghiệm'),
        ),
        migrations.AlterField(
            model_name='patienttest',
            name='test_status',
            field=models.CharField(choices=[('Pending', 'Đang chờ thanh toán'), ('Done', 'Đã xong'), ('Waiting', 'Đang chờ kết quả'), ('Cancelled', 'Đã hủy'), ('In Progress', 'Đang tiến hành')], default='Pending', max_length=20, verbose_name='Trạng thái xét nghiệm'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hospital.appointment', verbose_name='Lịch hẹn'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Mã đơn hàng'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Mã hóa đơn thanh toán'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('banking', 'Chuyển khoản'), ('cash', 'Tiền mặt')], max_length=50, null=True, verbose_name='Phương thức thanh toán'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('paid', 'Đã thanh toán')], default='unpaid', max_length=20, verbose_name='Trạng thái thanh toán'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian thanh toán'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('test', 'Xét nghiệm'), ('prescription', 'thuốc'), ('deposit', 'Đặt cọc')], default='deposit', max_length=20, null=True, verbose_name='Loại thanh toán'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tổng số tiền'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='vnp_create_date',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Ngày tạo VNPAY'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số tiền'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='detail_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Mã chi tiết thanh toán'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='detail_method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phương thức thanh toán'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='detail_status',
            field=models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('paid', 'Đã thanh toán')], default='unpaid', max_length=20, verbose_name='Trạng thái chi tiết thanh toán'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='hospital.payment', verbose_name='Hóa đơn thanh toán'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='service_id',
            field=models.IntegerField(verbose_name='Mã dịch vụ'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='service_name',
            field=models.CharField(max_length=255, verbose_name='Tên dịch vụ'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='service_type',
            field=models.CharField(max_length=50, verbose_name='Loại dịch vụ'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(max_length=50, verbose_name='Liều lượng sử dụng'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='duration',
            field=models.CharField(max_length=128, verbose_name='Thời gian sử dụng'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(max_length=50, verbose_name='Tần suất sử dụng'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='instructions',
            field=models.TextField(verbose_name='Hướng dẫn sử dụng'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='hospital.medication', verbose_name='Thuốc'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Mã đơn thuốc'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription_quantity',
            field=models.IntegerField(verbose_name='Số lượng thuốc'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='hospital.medicalrecord', verbose_name='Hồ sơ bệnh án'),
        ),
    ]
