# Generated by Django 5.1.7 on 2025-06-10 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_alter_appointment_options_alter_labtest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='otpusers',
            table='otp_users',
        ),
    ]
