# Generated by Django 5.1.7 on 2025-06-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_alter_user_address_alter_user_birth_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='detail_quantity',
            field=models.IntegerField(default=1, verbose_name='Số lượng dịch vụ'),
        ),
    ]
