# Generated by Django 5.1.7 on 2025-06-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_paymentdetail_detail_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='detail_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Số lượng dịch vụ'),
        ),
    ]
