# Generated by Django 5.1.7 on 2025-06-15 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0016_alter_paymentdetail_detail_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='detail_method',
        ),
    ]
