# Generated by Django 5.1.7 on 2025-06-15 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0017_remove_paymentdetail_detail_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medication',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='prescription_quantity',
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescription_status',
            field=models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('paid', 'Đã thanh toán'), ('completed', 'Đã nhận (hoàn tất)')], default='unpaid', max_length=20, verbose_name='Trạng thái đơn thuốc'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='instructions',
            field=models.TextField(verbose_name='Lời dặn của bác sĩ'),
        ),
        migrations.CreateModel(
            name='PrescriptionDetail',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã chi tiết thuốc')),
                ('quantity', models.IntegerField(verbose_name='Số lượng')),
                ('dosage', models.CharField(max_length=50, verbose_name='Liều dùng')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_details', to='hospital.medication', verbose_name='Thuốc')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='hospital.prescription', verbose_name='Đơn thuốc')),
            ],
            options={
                'verbose_name': 'Chi tiết thuốc',
                'verbose_name_plural': 'Chi tiết thuốc',
                'db_table': 'prescription_details',
            },
        ),
    ]
