# Generated by Django 5.1.7 on 2025-06-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_remove_prescription_dosage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienttest',
            name='test_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày xét nghiệm'),
        ),
    ]
