# Generated by Django 5.1.7 on 2025-06-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_alter_patienttest_test_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescription_status',
            field=models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('paid', 'Đã thanh toán'), ('done', 'Đã nhận (hoàn tất)')], default='unpaid', max_length=20, verbose_name='Trạng thái đơn thuốc'),
        ),
        migrations.AlterField(
            model_name='prescriptiondetail',
            name='dosage',
            field=models.CharField(max_length=100, verbose_name='Liều dùng'),
        ),
    ]
