# Generated by Django 5.1.7 on 2025-06-16 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_alter_prescription_prescription_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='user',
            name='img',
        ),
        migrations.RemoveField(
            model_name='user',
            name='specialty',
        ),
        migrations.CreateModel(
            name='ProfileDoctor',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã hồ sơ bác sĩ')),
                ('specialty', models.CharField(max_length=50, verbose_name='Chuyên khoa')),
                ('degree', models.CharField(max_length=50, verbose_name='Bằng cấp')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Ảnh đại diện')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hồ sơ bác sĩ',
                'verbose_name_plural': 'Hồ sơ bác sĩ',
                'db_table': 'profile_doctor',
            },
        ),
    ]
