# Generated by Django 5.1.7 on 2025-06-16 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_remove_user_degree_remove_user_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescriptiondetail',
            old_name='detail_id',
            new_name='detail_p_id',
        ),
        migrations.AlterModelTable(
            name='prescription',
            table='prescriptions',
        ),
    ]
